mongo:
  uri: 'mongodb://127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/ginchat?replicaSet=rs0'
  debug: true

redis:
  addr: 'localhost:6379'
  password: ''
  db: 1
  poolSize: 30
  minIdleConns: 30
