info:
  contact: {}
paths:
  /user:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: GetAll
      tags:
      - User
swagger: "2.0"
