version: '3.7'
services:
  mongo1:
      image: mongo:5.0.18
      restart: always
      ports:
        - 27017:27017
      volumes:
        - ./data/mongo1:/data/db
      command: mongod --replSet "rs0" --bind_ip_all

  mongo2:
    image: mongo:5.0.18
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data/mongo2:/data/db
    command: mongod --replSet "rs0" --bind_ip_all
